name: Python CI

on:
  push:
    branches: [ "main" ]
    paths-ignore:
      - 'README.md'
      - 'LICENSE'
      - '.gitignore'
      - 'CONTRIBUTING.md'
      - '.github/ISSUE_TEMPLATE/**'
  pull_request:
    branches: [ "main" ]
    paths-ignore:
      - 'README.md'
      - 'LICENSE'
      - '.gitignore'
      - 'CONTRIBUTING.md'
      - '.github/ISSUE_TEMPLATE/**'

jobs:
  test:
    name: tests (py${{ matrix.python-version }})
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ["3.10", "3.11", "3.12"]

    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: ${{ matrix.python-version }}
      - run: python -m pip install --upgrade pip
      - run: pip install -e ".[dev]"
      - run: pytest -q

  ci:
    name: ci
    runs-on: ubuntu-latest
    needs: test         # if any matrix job fails, this job is SKIPPED (not success)
    steps:
      - run: echo "All matrix jobs succeeded."
